-- M2 · Publish FLR_READINESS_01 version 1.0.0-pilot.
-- The definition is the exact JSON printed by app/scripts/export-definition.mjs
-- from app/src/engine/definitions.ts. Once published it cannot be edited; a
-- wording or scoring change is a new version (see freeze_published_version).
-- Wording is a DRAFT pending Randy's clinical approval (approval_note).

insert into public.assessment_versions (assessment_id, version_label, algorithm_version, status, definition, approval_note, published_at)
select a.id, '1.0.0-pilot', 'flr-readiness-alg-1.0.0', 'published', '{"code":"FLR_READINESS_01","version_label":"1.0.0-pilot","algorithm_version":"flr-readiness-alg-1.0.0","title":"Four-Lens readiness and ability check","scale":[{"value":"0","label":"Little or no limitation"},{"value":"1","label":"Mild limitation"},{"value":"2","label":"Moderate limitation"},{"value":"3","label":"Significant limitation"}],"questions":[{"q":1,"field":"recent_health_change","construct":"Recent health downturn or recovery","prompt":"In the past three months, how much has an illness, injury, surgery or hospital stay changed your usual activity?"},{"q":2,"field":"structure_change","construct":"Weight, muscle or body-composition change","prompt":"How much unplanned change have you noticed in your weight, muscle or body shape over the past six months?"},{"q":3,"field":"joint_limitation","construct":"Pain or stiffness limiting activity","prompt":"How much does joint pain or stiffness limit what you do?"},{"q":4,"field":"strength_task_limit","construct":"Lifting, carrying and chair-rise capacity","prompt":"How hard is it to lift or carry everyday loads, or to stand up from a chair without using your hands?"},{"q":5,"field":"rapid_force_limit","construct":"Power and rapid-force tasks","prompt":"How hard is it to move quickly when you need to, such as hurrying across a street or stepping to catch your balance?"},{"q":6,"field":"endurance_limit","construct":"Sustained activity tolerance","prompt":"How much does getting tired or out of breath limit how long you can stay active?"},{"q":7,"field":"mobility_limit","construct":"Movement access and mobility","prompt":"How much does limited movement, such as bending, reaching or turning, get in the way of daily tasks?"},{"q":8,"field":"independence_limit","construct":"Functional independence","prompt":"How much help or extra effort do you need for everyday tasks such as housework, shopping or getting dressed?"},{"q":9,"field":"balance_confidence_limit","construct":"Balance and fall confidence","prompt":"How much does worry about your balance or about falling limit what you do?"},{"q":10,"field":"recovery_participation_limit","construct":"Recovery and participation","prompt":"How much do slow recovery or low energy after activity keep you from things you want to do?"}],"orientation_code":"FLR_ORIENTATION_01","safety_gate":{"field":"safety_review_status","title":"Do new symptoms or medical instructions make physical activity feel unsafe for you right now?","options":[{"value":"no","label":"No"},{"value":"yes","label":"Yes"},{"value":"not_sure","label":"Not sure"}]},"notes":"Pilot routing thresholds, not validated clinical cut points. Orientation never changes a score; the safety answer changes the route only."}'::jsonb,
       'Pilot publication for internal and pilot testing. Item wording and thresholds await owner clinical approval before paid launch (Gate 2).',
       now()
from public.assessments a where a.code = 'FLR_READINESS_01'
on conflict (assessment_id, version_label) do nothing;
